### PR TITLE
fixed beam client node and added link to dev site 

### PR DESCRIPTION
**Pull request by TheBaconSpace**
:+1:

### CODE REVIEW

**Comment by JamyDev** [comment]
Please add the latest working version in there, this is not correct.

**Comment by connor4312** [comment]
Thanks!

**Comment by ProbablePrime** [comment]
Oh its https://developer.beam.pro not https://developer**s**.beam.pro

Looks like developer**s** still gets you there but is using a MCPro ssl cert which my browser complains about.

developer's ssl is fine.

**Comment by ttaylorr** [comment]
Thanks!

**Comment by MCProhosting-Matt** [comment]
I updated the readme here it should be developer.beam.pro

**Pull request merged**
