### PR TITLE
Fix formatting

### PR DESCRIPTION
**Pull request by 2Cubed**
- make indentation consistent
- fix typos
- fix link text

### CODE REVIEW

**Comment by ProbablePrime** [comment]
Looks good.

**Comment by SimonSchick** [comment]
neato

**Comment by SimonSchick** [comment]
Thanks for the contrib @2Cubed

**Comment by MattJustMatt** [comment]
Thanks @2Cubed. You're awesome.

**Comment by 2Cubed** [comment]
<3

**Pull request merged**
