### PR TITLE
Prep users for constellation

### PR DESCRIPTION
**Pull request by ProbablePrime**

### CODE REVIEW

**Comment by SimonSchick** [comment]
Do we really want to put PDFs on git?

**Comment by ProbablePrime** [comment]
It was on there before :D? Its small a few pages.

**Comment by MattJustMatt** [comment]
Not as a bad as videos! *cough* frontend

**Comment by MattJustMatt** [comment]
(That's totally my fault though)

**Comment by SimonSchick** [comment]
Eh, whatever, I'd prefer if we had a universal utility file hosting but this works.

**Comment by ProbablePrime** [comment]
We can make a public folder on the internal GDrive. I suppose. More important to get this out though.

**Comment by connor4312** [comment]
We can always use LFS

**Comment by MattJustMatt** [comment]
Where my @ttaylorr at? Haha.

**Comment by ProbablePrime** [comment]
This is out of scope now :) but cool.

**Comment by ProbablePrime** [comment]
@SimonSchick @MattJustMatt @connor4312 Are we good here? want to get this out so people can start looking into constellation.

**Comment by SimonSchick** [comment]
sure.

**Pull request merged**
