### PR TITLE
Sync is bad and you should feel bad

### PR DESCRIPTION
**Pull request by connor4312**
:wink:

### CODE REVIEW

**Comment by ttaylorr** [comment]
Haha, thank you for this!  We can probably remove the `import fs` statement above, since I don't think it's used anywhere in the file besides there.

**Comment by connor4312** [comment]
Done. Want me to throw eslint at this?

**Comment by ttaylorr** [comment]
If you want to, sure -- but probably best suited in a different PR.  I don't mind!

**Comment by connor4312** [comment]
Will do. Working on getting oauth registration in here.

**Pull request merged**
